/*
 * This file is automatically generated by scripts/seed.
 * Do not edit this file manually as your changes may be overwritten
 * by subsequent runs of the auto-generation script.
 */

export const topics = [];

export const data = [];
